# Generated by Django 5.0 on 2024-01-06 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowing_users',
            field=models.ManyToManyField(blank=True, related_name='borrow_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
